version: '3'

services:
  app:
    image: thecodingmachine/php:${PHP_VERSION:-7.2}-v2-fpm
    environment:
      PHP_INI_PHAR__READONLY: "Off"
      TYPO3_VERSION: ${TYPO3_VERSION:-^9.5}
    depends_on:
      - ssh-key
    volumes:
      - ./:/var/www/html
      - ssh-agent:/.ssh-agent

  ssh-agent:
    image: docksal/ssh-agent:1.3
    volumes:
      - ssh-agent:/.ssh-agent

  ssh-key:
    image: docksal/ssh-agent:1.3
    command: ['bash', '-c', 'ssh-add - </tmp/host-ssh/id_rsa']
    depends_on:
      - ssh-agent
    volumes:
      - $HOME/.ssh:/tmp/host-ssh:ro
      - ssh-agent:/.ssh-agent

volumes:
  ssh-agent:
